# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brief', models.TextField(default='nothing...', max_length=1024)),
                ('member_limit', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('friends', models.ManyToManyField(blank=True, related_name='my_friends', to='app.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_groups', models.ManyToManyField(to='app.UserGroup')),
            ],
        ),
        migrations.AddField(
            model_name='qqgroup',
            name='admin',
            field=models.ManyToManyField(related_name='group_admins', to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='qqgroup',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
        migrations.AddField(
            model_name='qqgroup',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='app.UserProfile'),
        ),
    ]
